### ISSUE TITLE
Unexpected type 'ForwardRef('ProductCategory')'. Postponed annotations bug

### ISSUE THREAD

**Issue by deknowny** [strawberry-graphql/strawberry#1500]
I have a model `Product` and a model `Wholesaler` with cross-referenced themselves in fields definitions. My `Product` model code:

```python
from __future__ import annotations

import typing

import strawberry

if typing.TYPE_CHECKING:
    from src.view.amount import Amount
    from src.view.wholesaler.single import Wholesaler
    from src.view.product.category import ProductCategory


@strawberry.type
class Product:
    id: strawberry.ID
    name: str
    category: "ProductCategory"
    amount: "Amount"
    retail_price: int
    wholesaler: "Wholesaler"
    wholesaler_price: int
    barcode: str
    comment: str
```
My `Wholesaler` model (another file)
```python
from __future__ import annotations

import typing

import strawberry

if typing.TYPE_CHECKING:
    from src.view.product.single import Product
    from src.view.product.sorting import ProductFilters


@strawberry.type
class Wholesaler:
    id: strawberry.ID
    name: str
    phone: str
    email: typing.Optional[str]
    comment: typing.Optional[str]

    @strawberry.field
    def products(self, filters: "ProductFilters") -> "Product":
        pass
```

And I get a error:
```shell
Traceback (most recent call last):
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/graphql/type/definition.py", line 735, in fields
    fields = resolve_thunk(self._fields)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/graphql/type/definition.py", line 264, in resolve_thunk
    return thunk() if callable(thunk) else thunk
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 278, in get_graphql_fields
    graphql_fields[field_name] = self.from_field(field)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 135, in from_field
    field_type = self.from_non_optional(field.type)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 259, in from_non_optional
    of_type = self.from_type(type_)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 464, in from_type
    raise TypeError(f"Unexpected type '{type_}'")
TypeError: Unexpected type 'ForwardRef('ProductCategory')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/an/Desktop/nto/grocery-server/src/__main__.py", line 5, in <module>
    uvicorn.run(
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/uvicorn/config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/an/Desktop/nto/grocery-server/src/app/main.py", line 3, in <module>
    from src.app.graphql import graphql_app
  File "/Users/an/Desktop/nto/grocery-server/src/app/graphql.py", line 8, in <module>
    schema = strawberry.Schema(Query, Mutation)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/strawberry/schema/schema.py", line 84, in __init__
    self._schema = GraphQLSchema(
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/graphql/type/schema.py", line 208, in __init__
    collect_referenced_types(query)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/graphql/type/schema.py", line 420, in collect_referenced_types
    collect_referenced_types(interface_type)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/graphql/type/schema.py", line 423, in collect_referenced_types
    collect_referenced_types(field.type)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/graphql/type/schema.py", line 422, in collect_referenced_types
    for field in named_type.fields.values():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 966, in __get__
    val = self.func(instance)
  File "/Users/an/Desktop/nto/grocery-server/.venv/lib/python3.8/site-packages/graphql/type/definition.py", line 737, in fields
    raise TypeError(f"{self.name} fields cannot be resolved. {error}")
TypeError: Product fields cannot be resolved. Unexpected type 'ForwardRef('ProductCategory')'
```
***
Suppose strawberry can't resolve postponed annotations when the model defined in another module. I also try removing quotes in the typing, but just get the same error with `None` instead `'ForwardRef('ProductCategory')'`. I can't remove `if typing.TYPE_CHECKING:` because these models reference themselves so I do not see a way to solve the problem
***
I'm using `0.93.4` version of strawberry

**Comment by patrick91** [comment]
Hi @deknowny! Can you try with LazyType? It allows to pass the module name too: https://github.com/strawberry-graphql/strawberry/blob/main/tests/types/test_lazy_types.py#L20

**Comment by deknowny** [comment]
@patrick91 Can you please explain how correctly use in such case? Like this?
```python
category: strawberry.LazyType["ProductCategory", "src.view.wholesaler.single"]
```
Unfortunately
```shell
TypeError: Product fields cannot be resolved. 'ProductCategory'
```

**Comment by deknowny** [comment]
My `ProductCategory`:
```python
import enum

import strawberry


@strawberry.enum
class ProductCategory(enum.Enum):
    BREAD = "BREAD"
    DRINKS = "DRINKS"
    FRUIT = "FRUIT"
    MEAT = "MEAT"
    MILK = "MILK"
```

**Comment by patrick91** [comment]
@deknowny that should work 🤔 can you replicate with a couple of files? maybe the module path is wrong?

**Comment by deknowny** [comment]
@patrick91 I guess if it wasn't a correct module path it couldn't be resolved to an enum at all.

Sorry, what do you mean in "replicate with a couple of files"?

***
Now I specially try to pass invalid path and I got `TypeError: Product fields cannot be resolved. 'ProductCategory'` or `TypeError: Product fields cannot be resolved. No module named 'src.view.product.categor'` and it is not such error

**Comment by deknowny** [comment]
By the way, `amount: strawberry.LazyType["Amount", "src.view.amount"]` works correctly. Seem like the bug with enums only

**Comment by deknowny** [comment]
@patrick91 I traced it with breakpoint and see this:
In line where lazy type resolved: https://github.com/strawberry-graphql/strawberry/blob/a08b8beddcb7564c4b55fadbcb7a4caba8fbbc70/strawberry/schema/schema_converter.py#L458
This condition is `False`: https://github.com/strawberry-graphql/strawberry/blob/a08b8beddcb7564c4b55fadbcb7a4caba8fbbc70/strawberry/schema/schema_converter.py#L441

**Comment by patrick91** [comment]
@deknowny I just did a test locally and seems to be working fine, but maybe you have something different than me 🤔 

what is `type_` in your case? :) PS. we can chat on discord if it is easier :D

**Comment by deknowny** [comment]
@patrick91 `LazyType(type_name='ProductCategory', module='src.view.product.category', package=None)` in first call and `<enum 'ProductCategory'>` in the second

Jle4enka#3075
