### ISSUE TITLE
Type not registering having circular dependency

### ISSUE THREAD

**Issue by basvandriel** [strawberry-graphql/strawberry#1580]
I have a simple `User` type, having a bi-directional relation to a `Practice` type;

```
import strawberry
from datetime import datetime
from typing import ForwardRef, Optional, List, TYPE_CHECKING

if TYPE_CHECKING:
    from ..practice.graphql_type import Practice


@strawberry.type
class User:
    id: strawberry.ID
    email: str
    practices: List["Practice"]
```

The relation works, as tested with SQLAlchemy.

```
import strawberry

from typing import Optional, List
from datetime import datetime
from ..authentication.user_type import User


@strawberry.type
class Practice:
    id: strawberry.ID
    created_by: Optional[User]
```

Same thing goes for the `Practice` just a simple `created_by` relation. When running, or trying too export the schema; I get this error;

```
Traceback (most recent call last):
  File "/project/venv/lib/python3.8/site-packages/graphql/type/definition.py", line 735, in fields
    fields = resolve_thunk(self._fields)
  File "/project/venv/lib/python3.8/site-packages/graphql/type/definition.py", line 264, in resolve_thunk
    return thunk() if callable(thunk) else thunk
  File "/project/venv/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 280, in get_graphql_fields
    graphql_fields[field_name] = self.from_field(field)
  File "/project/venv/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 136, in from_field
    field_type = self.from_non_optional(field.type)
  File "/project/venv/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 261, in from_non_optional
    of_type = self.from_type(type_)
  File "/project/venv/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 469, in from_type
    raise TypeError(f"Unexpected type '{type_}'")
TypeError: Unexpected type 'None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/project/venv/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 849, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 324, in __init__
    self._load_unlocked()
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 350, in _load_unlocked
    self._app = rv = self.loader()
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 410, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/project/app.py", line 1, in <module>
    from src import create_app
  File "/project/src/__init__.py", line 4, in <module>
    from .schema import schema
  File "/project/src/schema.py", line 49, in <module>
    schema = Schema(
  File "/project/venv/lib/python3.8/site-packages/strawberry/schema/schema.py", line 84, in __init__
    self._schema = GraphQLSchema(
  File "/project/venv/lib/python3.8/site-packages/graphql/type/schema.py", line 208, in __init__
    collect_referenced_types(query)
  File "/project/venv/lib/python3.8/site-packages/graphql/type/schema.py", line 423, in collect_referenced_types
    collect_referenced_types(field.type)
  File "/project/venv/lib/python3.8/site-packages/graphql/type/schema.py", line 422, in collect_referenced_types
    for field in named_type.fields.values():
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/project/venv/lib/python3.8/site-packages/graphql/type/definition.py", line 737, in fields
    raise TypeError(f"{self.name} fields cannot be resolved. {error}")
TypeError: User fields cannot be resolved. Unexpected type 'None'
```

What's wrong?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1580">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1580/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1580/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
hi @basvandriel!

We probably need a better error message for this, the issue it that in your file you have this:

```
if TYPE_CHECKING:
    from ..practice.graphql_type import Practice
```

this tells **only** type checkers where to find `Practice`, but it won't affect runtime behaviour
so when running strawberry Practice is not defined.

One way to fix this is to use lazy types, which is a way to tell strawberry where a class comes from:

```
import strawberry
from datetime import datetime
from typing import ForwardRef, Optional, List, TYPE_CHECKING

if TYPE_CHECKING:
    from ..practice.graphql_type import Practice


@strawberry.type
class User:
    id: strawberry.ID
    email: str
    practices: List[strawberry.LazyType["Practice", "path.to.graphql_type.Practice"]]
```

**Comment by basvandriel** [comment]
Well, it definitly worked while using that ` LazyType`, thanks @patrick91 !
However, I tried this, found in countless tutorials/articles regarding circular imports

```
from datetime import datetime
from typing import Optional, List

import strawberry


# Importing the module entirely
import src.practice.graphql_type


@strawberry.type
class User:
    id: strawberry.ID
    practices: List[src.practice.graphql_type.Practice]
```

This results in this error;

```
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "/project/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/project/venv/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/project/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 849, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 324, in __init__
    self._load_unlocked()
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 350, in _load_unlocked
    self._app = rv = self.loader()
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 410, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/project/venv/lib/python3.8/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/project/app.py", line 1, in <module>
    from src import create_app
  File "/project/src/__init__.py", line 4, in <module>
    from .schema import schema
  File "/project/src/schema.py", line 7, in <module>
    from src.practice.mutation.create_practice import create_practice
  File "/project/src/practice/mutation/create_practice.py", line 6, in <module>
    from ..graphql_type import Practice as Type
  File "/project/src/practice/graphql_type.py", line 6, in <module>
    from ..authentication.user_type import User
  File "/project/src/authentication/user_type.py", line 14, in <module>
    class User:
  File "/project/src/authentication/user_type.py", line 18, in User
    practices: List[src.practice.graphql_type.Practice]
AttributeError: module 'src.practice' has no attribute 'graphql_type'
```

What seems to cause this? And why isn't it possible like this?

**Comment by patrick91** [comment]
Have you tried with just `import src.practice`?

To be honest I'm not 100% sure how the python import system works when you import something like that :D

**Comment by basvandriel** [comment]
> Have you tried with just `import src.practice`?
> 
> 
> 
> To be honest I'm not 100% sure how the python import system works when you import something like that :D

I'll check tommorow! Aren't there any example apps using this lib with bi-directional relationships?

**Comment by patrick91** [comment]
> > Have you tried with just `import src.practice`?
> > To be honest I'm not 100% sure how the python import system works when you import something like that :D
> 
> I'll check tommorow! Aren't there any example apps using this lib with bi-directional relationships?

I think so, but I've mostly seen LazyTypes being used in that case, for example we use it here: https://github.com/pythonitalia/pycon/search?q=lazytype

**Comment by basvandriel** [comment]
Hey @patrick91 , I tried using only `import src.authentication`, unfortunately, the same error showed up;

`AttributeError: module 'src.practice' has no attribute 'graphql_type'`

The `LazyType` thing works as expected. Is this still fixable with the "only-python", I'm trying to understand why it's possible like that.

**Comment by arunchandrapant** [comment]
Thanks @patrick91. LazyType works for me too. Also importing module completely does not work for me. It would be good if 'LazyType' was present in the docs. I couldn't find it and spent quiet some time searching for this.

**Comment by patrick91** [comment]
> Thanks @patrick91. LazyType works for me too. Also importing module completely does not work for me. It would be good if 'LazyType' was present in the docs. I couldn't find it and spent quiet some time searching for this.

Yes, I haven't documented it yet because I hoped there's better ways in order to do that 😊

By the way would you be interested in sending a PR to document LazyTypes?

**Comment by DoctorJohn** [comment]
Lazy type docs were added in #2158
