### ISSUE TITLE
File upload using multipart/form-data errors 

### ISSUE THREAD

**Issue by Phat-Loc** [strawberry-graphql/strawberry#1715]
I tried to Strawberry with FastAPI integration. Why is strawberry trying to do a json.loads on mulitpart_data? When I upload a file from the browser as a multipart/form-data I get the following error:

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/phat/projects/excel-file-manager/venv/lib/python3.10/site-packages/strawberry/fastapi/router.py", line 165, in handle_http_query
    operations = json.loads(multipart_data.get("operations", {}))
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict`

**Comment by estyxx** [comment]
Hi, 
Can you give us some details: how did you implement the mutation, the query you are trying to do and how did you pass the variables? 


The file upload specifications are a bit different, according to the [GraphQL multipart request specification](https://github.com/jaydenseric/graphql-multipart-request-spec#graphql-multipart-request-specification): 
in the `operations` files must be replaced with null and in `map` **For each file, the key is the file multipart form field name and the value is an array of operations paths.** 
it's harder to explain in words... but you can see some examples [here in our tests](https://github.com/strawberry-graphql/strawberry/blob/main/tests/fastapi/test_upload.py#L17:L18) hope those help to understand :)

**Comment by estyxx** [comment]
Hey @Phat-Loc are you still having this problem? 
Also meanwhile [here](https://github.com/strawberry-graphql/strawberry/pull/1717) I have updated the docs with some examples :)

**Comment by Phat-Loc** [comment]
It is working now. I looked at the test code for Strawberry and just made the same request via Javascript that the test code does. Thanks!
