### ISSUE TITLE
Mypy Plugin Issue and list unpacking

### ISSUE THREAD

**Issue by motherofcoconuts** [strawberry-graphql/strawberry#1828]
I am running into an issue with the strawberry plugin when using list unpacking to define a union type.

Command: `dmypy run -- --follow-imports=skip`
Results:
```
Daemon crashed!
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 229, in serve
  File "mypy/dmypy_server.py", line 272, in run_command
  File "mypy/dmypy_server.py", line 331, in cmd_run
  File "mypy/dmypy_server.py", line 391, in check
  File "mypy/dmypy_server.py", line 528, in fine_grained_increment
  File "mypy/server/update.py", line 245, in update
  File "mypy/server/update.py", line 328, in update_one
  File "mypy/server/update.py", line 393, in update_module
  File "mypy/server/update.py", line 602, in update_module_isolated
  File "mypy/semanal_main.py", line 78, in semantic_analysis_for_scc
  File "mypy/semanal_main.py", line 199, in process_top_levels
  File "mypy/semanal_main.py", line 326, in semantic_analyze_target
  File "mypy/semanal.py", line 414, in refresh_partial
  File "mypy/semanal.py", line 425, in refresh_top_level
  File "mypy/semanal.py", line 5222, in accept
  File "mypy/errors.py", line 902, in report_internal_error
  File "mypy/semanal.py", line 5220, in accept
  File "mypy/nodes.py", line 1155, in accept
  File "mypy/semanal.py", line 2091, in visit_assignment_stmt
  File "mypy/semanal.py", line 2377, in apply_dynamic_class_hook
  File "/Users/ryanhoulihan/Baton/anton-v2/.venv/lib/python3.10/site-packages/strawberry/ext/mypy_plugin.py", line 181, in union_hook
    tuple(_get_type_for_expr(x, ctx.api) for x in types.items)
  File "/Users/ryanhoulihan/Baton/anton-v2/.venv/lib/python3.10/site-packages/strawberry/ext/mypy_plugin.py", line 181, in <genexpr>
    tuple(_get_type_for_expr(x, ctx.api) for x in types.items)
  File "/Users/ryanhoulihan/Baton/anton-v2/.venv/lib/python3.10/site-packages/strawberry/ext/mypy_plugin.py", line 148, in _get_type_for_expr
    raise ValueError(f"Unsupported expression {type(expr)}")
ValueError: Unsupported expression <class 'mypy.nodes.StarExpr'>
```

Minimal code set to reproduce:
```
@strawberry.type
class UsernameAlreadyTaken():
    message: str = "Username taken."

@strawberry.type
class InvalidEmailAddress():
    message: str = "Email address is invalid."

UserErrors = (
    UsernameAlreadyTaken,
    InvalidEmailAddress,
)

UserMutationResponse = strawberry.union(
    name="UserResponse", types=(User, *UserErrors)
)
```

Current work around to prevent the crashing from occuring:
```
UserMutationTypes = (User, *UserErrors)
UserMutationResponse = strawberry.union(
    name="UserResponse", types=(User, *UserErrors)
)

```

**Comment by patrick91** [comment]
Thanks for the report! I'll take a look at this during the week :)

**Comment by patrick91** [comment]
We now support Annotated for unions so I think this issue is not valid anymore 😊
