### ISSUE TITLE
New directive printing improvements have caused issues with Apollo Federation

### ISSUE THREAD

**Issue by jceresini** [strawberry-graphql/strawberry#1943]
The changes in [this PR](https://github.com/strawberry-graphql/strawberry/pull/1723), which are awesome by the way, seem to have introduced an issue when using strawberry with apollo federation.

Our schema's now have the following:

```
directive @key(fields: _FieldSet!, resolvable: Boolean) on OBJECT | INTERFACE
```

And when Apollo tries to federate it throws the following error:

```
(node:28) UnhandledPromiseRejectionWarning: Error: A valid schema couldn't be composed. The following composition errors were found:
	[customers-api] Unknown type _FieldSet
	[security-events-api] Unknown type _FieldSet
	[resources-api] Unknown type _FieldSet
    at IntrospectAndCompose.createSupergraphFromSubgraphList (/app/node_modules/@apollo/gateway/dist/supergraphManagers/IntrospectAndCompose/index.js:73:19)
    at IntrospectAndCompose.updateSupergraphSdl (/app/node_modules/@apollo/gateway/dist/supergraphManagers/IntrospectAndCompose/index.js:65:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async IntrospectAndCompose.initialize (/app/node_modules/@apollo/gateway/dist/supergraphManagers/IntrospectAndCompose/index.js:28:36)
    at async ApolloGateway.initializeSupergraphManager (/app/node_modules/@apollo/gateway/dist/index.js:325:28)
    at async ApolloGateway.load (/app/node_modules/@apollo/gateway/dist/index.js:254:13)
    at async SchemaManager.start (/app/node_modules/apollo-server-core/dist/utils/schemaManager.js:42:28)
    at async ApolloServer._start (/app/node_modules/apollo-server-core/dist/ApolloServer.js:182:30)
    at async ApolloServer.start (/app/node_modules/apollo-server-core/dist/ApolloServer.js:167:16)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.82s.
```

It looks like we just need to make sure the `_FieldSet` scalar is defined in the schema as well. I attempted to resolve the issue by adding the following, but it resulted in a new error:

```python
from strawberry.federation.schema_directives import FieldSet

@strawberry.type
class Query:
    dummy: Optional[FieldSet] = None

[...]
```
New error from apollo:

```
(node:29) UnhandledPromiseRejectionWarning: Error: A valid schema couldn't be composed. The following composition errors were found:
	[customers-api] Invalid definition for directive "@key": argument "resolvable" should have default value true but found default value null
	[security-events-api] Invalid definition for directive "@key": argument "resolvable" should have default value true but found default value null
	[resources-api] Invalid definition for directive "@key": argument "resolvable" should have default value true but found default value null
```

**Comment by patrick91** [comment]
hi @jceresini I think I have an idea on how to fix this, I'm at PyCon Italia at the moment, but hopefully I'll be able to do something by the end of the week 😊

**Comment by jceresini** [comment]
Awesome, thanks! If you need, I can put together a simplified example demonstrating the issue. It was late when I ran into it so I wrote this up quickly in case anyone else has run into it.

**Comment by valeriob23** [comment]
Any news on this? I'm facing the same issue also with the latest 0.114.6 version.

**Comment by patrick91** [comment]
@valeriob23 @jceresini sorry both for the late reply, I just did a PR that should fix this, would you be able to run a quick test for me and see if works for you too?

```
poetry add strawberry-graphql==0.116.2.dev.1656872058
```

**Comment by valeriob23** [comment]
yep, it resolves on my side. Thanks a lot for the support!

**Comment by patrick91** [comment]
@valeriob23 thanks for checking! I'll merge the PR then 😊
