### ISSUE TITLE
from __future__ import annotations incompatible with self referencing

### ISSUE THREAD

**Issue by eddysen** [strawberry-graphql/strawberry#1993]
Trying to create a strawberry type (addition of `from __future__ import annotations` and the use of `strawberry.auto`) results in a traceback. The strawberry is resolved as self referencing to the class itself and raise an exception.

## Describe the Bug
Here is the content of the strawberry type declaration file
```
from __future__ import annotations
from typing import List
import strawberry
from main.apis.graphql.types.produit_out_type import ProduitOutType

from main.schemas.categorie_produit_out_schema import CategorieProduitOut
@strawberry.experimental.pydantic.type(model=CategorieProduitOut)
class CategorieProduitOutType:
  id: strawberry.auto
  parent: strawberry.auto
  nom: strawberry.auto
  description: strawberry.auto
  info_bulle: strawberry.auto
  image: strawberry.auto
  nom_d_affichage_categorie: strawberry.auto
  produits: List[ProduitOutType]
```

Here is the content of the corresponding  pydantic schema declaration file
```
from uuid import UUID
from pydantic import BaseModel
from typing import List, Optional

from main.schemas.produit_out_schema import ProduitOut

class CategorieProduitOut(BaseModel):
  id: UUID
  parent: 'CategorieProduitOut'=None # a forward self referencing
  nom: str
  description: Optional[str] = None
  info_bulle: Optional[str] = None
  image: Optional[str] = None
  nom_d_affichage_categorie: Optional[str] = None
  produits: List[ProduitOut]

```

Here is what i have as traceback:
```

 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 800, in fields
     fields = resolve_thunk(self._fields)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 300, in resolve_thunk
     return thunk() if callable(thunk) else thunk
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema_converter.py", line 366, in <lambda>
     fields=lambda: self.get_graphql_fields(object_type),
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema_converter.py", line 272, in get_graphql_fields
     field_converter=self.from_field,
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema_converter.py", line 263, in _get_thunk_mapping
     thunk_mapping[name_converter(f)] = field_converter(f)
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema_converter.py", line 197, in from_field
     field_type = cast(GraphQLOutputType, self.from_maybe_optional(field.type))
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema_converter.py", line 517, in from_maybe_optional
     return GraphQLNonNull(self.from_type(type_))
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema_converter.py", line 549, in from_type
     raise TypeError(f"Unexpected type '{type_}'")
 TypeError: Unexpected type 'typing_extensions.Annotated[typing.Any, <auto>]'
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/bin/alembic", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 590, in main
     CommandLine(prog=prog).main(argv=argv)
   File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 584, in main
     self.run_cmd(cfg, options)
   File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 564, in run_cmd
     **dict((k, getattr(options, k, None)) for k in kwarg),
   File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 322, in upgrade
     script.run_env()
   File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 569, in run_env
     util.load_python_file(self.dir, "env.py")
   File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
     module = load_module_py(module_id, path)
   File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
     spec.loader.exec_module(module)  # type: ignore
   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "alembic/env.py", line 24, in <module>
     from main.database import  engine, Base
   File "./main/__init__.py", line 251, in <module>
     schema = strawberry.Schema(query=Query,mutation=Mutation)
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema.py", line 104, in __init__
     types=graphql_types,
   File "/usr/local/lib/python3.7/site-packages/graphql/type/schema.py", line 224, in __init__
     collect_referenced_types(query)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/schema.py", line 433, in collect_referenced_types
     collect_referenced_types(field.type)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/schema.py", line 433, in collect_referenced_types
     collect_referenced_types(field.type)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/schema.py", line 432, in collect_referenced_types
     for field in named_type.fields.values():
   File "/usr/local/lib/python3.7/site-packages/graphql/pyutils/cached_property.py", line 30, in __get__
     value = obj.__dict__[self.func.__name__] = self.func(obj)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 803, in fields
     raise cls(f"{self.name} fields cannot be resolved. {error}") from error
 TypeError: CategorieProduitOutType fields cannot be resolved. Unexpected type 'typing_extensions.Annotated[typing.Any, <auto>]'
```

i'm having a `TypeError: Unexpected type 'typing_extensions.Annotated[typing.Any, <auto>]'`. The bug is similar to this found in this report :
https://github.com/strawberry-graphql/strawberry/issues/1586

## System Information

 - Python: 3.7 
 - strawberry-graphql==0.93.13
 - OS: Docker container from python:3.7

**Comment by patrick91** [comment]
@eddysen I can reproduce this issue, let me see if there's a quick way to fix it 😊

**Comment by eddysen** [comment]
@patrick91 , when using the pre-release `strawberry-graphql==0.116.5.dev.1657033844 `, 

1- using `from __future__ import annotations` with `strawberry.auto` is **ok**
2- But using forward self-referencing is **not ok**

To test the point 2 : use this code:
```

from __future__ import annotations
from typing import List, Optional
import strawberry
from main.apis.graphql.types.produit_out_type import ProduitOutType

from main.schemas.categorie_produit_out_schema import CategorieProduitOut
@strawberry.experimental.pydantic.type(model=CategorieProduitOut)
class CategorieProduitOutType:
  id: strawberry.auto
  parent: CategorieProduitOutType # <-- Forward self-reference, same error using __name__
  nom: strawberry.auto
  description: strawberry.auto
  info_bulle: strawberry.auto
  image: strawberry.auto
  nom_d_affichage_categorie: strawberry.auto
  produits: List[ProduitOutType]
```

The traceback then is:
```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 800, in fields
     fields = resolve_thunk(self._fields)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 300, in resolve_thunk
     return thunk() if callable(thunk) else thunk
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema_converter.py", line 395, in <lambda>
     fields=lambda: self.get_graphql_fields(object_type),
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema_converter.py", line 295, in get_graphql_fields
     field_converter=self.from_field,
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema_converter.py", line 283, in _get_thunk_mapping
     raise UnresolvedFieldTypeError(f.name)
 strawberry.exceptions.UnresolvedFieldTypeError: Could not resolve the type of 'parent'. Check that the class is accessible from the global module scope.
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/bin/alembic", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 590, in main
     CommandLine(prog=prog).main(argv=argv)
   File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 584, in main
     self.run_cmd(cfg, options)
   File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 564, in run_cmd
     **dict((k, getattr(options, k, None)) for k in kwarg),
   File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 322, in upgrade
     script.run_env()
   File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 569, in run_env
     util.load_python_file(self.dir, "env.py")
   File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
     module = load_module_py(module_id, path)
   File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
     spec.loader.exec_module(module)  # type: ignore
   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "alembic/env.py", line 24, in <module>
     from main.database import  engine, Base
   File "./main/__init__.py", line 251, in <module>
     schema = strawberry.Schema(query=Query,mutation=Mutation)
   File "/usr/local/lib/python3.7/site-packages/strawberry/schema/schema.py", line 106, in __init__
     GraphQLCoreConverter.DEFINITION_BACKREF: self,
   File "/usr/local/lib/python3.7/site-packages/graphql/type/schema.py", line 224, in __init__
     collect_referenced_types(query)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/schema.py", line 433, in collect_referenced_types
     collect_referenced_types(field.type)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/schema.py", line 433, in collect_referenced_types
     collect_referenced_types(field.type)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/schema.py", line 432, in collect_referenced_types
     for field in named_type.fields.values():
   File "/usr/local/lib/python3.7/site-packages/graphql/pyutils/cached_property.py", line 30, in __get__
     value = obj.__dict__[self.func.__name__] = self.func(obj)
   File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 803, in fields
     raise cls(f"{self.name} fields cannot be resolved. {error}") from error
 TypeError: CategorieProduitOutType fields cannot be resolved. Could not resolve the type of 'parent'. Check that the class is accessible from the global module scope.
```

**Comment by patrick91** [comment]
@eddysen thanks for trying the pre-release, I'll see if that's quick to fix too 😊

**Comment by patrick91** [comment]
@eddysen I think this is going to take more time to fix, I have a workaround for you though:

```python
@strawberry.experimental.pydantic.type(model=CategorieProduitOut)
class CategorieProduitOutType:
    id: strawberry.auto
    # you can use LazyType for self referencing types:
    parent: strawberry.LazyType["CategorieProduitOutType", "demo"]
```

hope this unblocks you, let me know if it doesn't work :)

**Comment by eddysen** [comment]
Hello @patrick91 , thank a lot for the support, **it solves my problem**. Here is the final version of the code corresponding:
```
@strawberry.experimental.pydantic.type(model=CategorieProduitOut)
class CategorieProduitOutType:
  id: strawberry.auto
  parent: Optional[strawberry.LazyType["CategorieProduitOutType",".categorie_produit_out_type"]]=None
```
where **.categorie_produit_out_type.py** is the file where the class code resides.
