### ISSUE TITLE
Bug: Can't have a list of Type on Input Type.

### ISSUE THREAD

**Issue by ronaldnwilliams** [strawberry-graphql/strawberry#2241]
## Describe the Bug
When I try to add a list field to an Input type, I get a TypeError.

```
@strawberry.type
class Fruit:
    name: str

@strawberry.type
class OtherType:
    name: str


@strawberry.input
class FruitInput:
    name: str
    field_list: list[OtherType] = strawberry.field(default_factory=list)


class FruitResolver:
    @classmethod
    def create(cls, fruit_input: FruitInput):
        return Fruit(name=fruit_input.name)


@strawberry.type
class Mutation:
    create_fruit: Fruit = strawberry.field(resolver=FruitResolver.create)


schema = strawberry.Schema(mutation=Mutation)
```

Stacktrace
```
$ strawberry export-schema main
Traceback (most recent call last):
  File "graphql/type/definition.py", line 1456, in fields
    fields = resolve_thunk(self._fields)
  File "graphql/type/definition.py", line 300, in resolve_thunk
    return thunk() if callable(thunk) else thunk
  File "strawberry/schema/schema_converter.py", line 321, in <lambda>
    fields=lambda: self.get_graphql_input_fields(type_definition),
  File "strawberry/schema/schema_converter.py", line 302, in get_graphql_input_fields
    return self._get_thunk_mapping(
  File "strawberry/schema/schema_converter.py", line 287, in _get_thunk_mapping
    thunk_mapping[name_converter(f)] = field_converter(f)
  File "strawberry/schema/schema_converter.py", line 251, in from_input_field
    return GraphQLInputField(
  File "graphql/type/definition.py", line 1525, in __init__
    raise TypeError("Input field type must be a GraphQL input type.")
TypeError: Input field type must be a GraphQL input type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/bin/strawberry", line 8, in <module>
    sys.exit(run())
  File "click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "strawberry/cli/commands/export_schema.py", line 21, in export_schema
    schema_symbol = load_schema(schema, app_dir)
  File "strawberry/cli/utils/__init__.py", line 13, in load_schema
    schema_symbol = import_module_symbol(schema, default_symbol_name="schema")
  File "strawberry/utils/importer.py", line 15, in import_module_symbol
    module = importlib.import_module(module_name)
  File "/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "strawberry_playground/./main.py", line 59, in <module>
    schema = strawberry.Schema(query=Query, mutation=Mutation)
  File "strawberry/schema/schema.py", line 111, in __init__
    self._schema = GraphQLSchema(
  File "graphql/type/schema.py", line 226, in __init__
    collect_referenced_types(mutation)
  File "graphql/type/schema.py", line 435, in collect_referenced_types
    collect_referenced_types(arg.type)
  File "graphql/type/schema.py", line 438, in collect_referenced_types
    for field in named_type.fields.values():
  File "/functools.py", line 993, in __get__
    val = self.func(instance)
  File "graphql/type/definition.py", line 1459, in fields
    raise cls(f"{self.name} fields cannot be resolved. {error}") from error
TypeError: FruitInput fields cannot be resolved. Input field type must be a GraphQL input type.

```

## System Information

 - Operating system: MacOs Monterey
 - Strawberry version (if applicable): 0.133.5

**Comment by patrick91** [comment]
Hi @ronaldnwilliams, input fields can only be input types or scalars (this is from the GraphQL spec). To fix your example you need to change `OtherType` to use `strawberry.input` :)

https://play.strawberry.rocks/?gist=7d868d9480a54735f0236c5f1dd92eee

let me know if that doesn't work for you!

**Comment by ronaldnwilliams** [comment]
@patrick91  that makes sense. Thank you!
