### ISSUE TITLE
strawberry.enum_value breaks input parsing

### ISSUE THREAD

**Issue by N-Maas** [strawberry-graphql/strawberry#2305]
## Describe the Bug

If `strawberry.enum_value` is used for an enum variant, parsing this variant as input of a query fails.

Consider the following example:
```python
from enum import Enum
import traceback

import strawberry

@strawberry.enum
class TestEnum(Enum):
    A = strawberry.enum_value("A")
    B = "B"

@strawberry.type
class Query:
    @strawberry.field
    def receive_enum(self, test: TestEnum) -> int:
        return 0

schema = strawberry.Schema(query=Query)

query = """
    {
        receiveEnum(test: A)
    }
""" # works if A is replaced by B
result = schema.execute_sync(query)

if result.errors:
    [error] = result.errors
    orig = error.original_error
    print(error)
    traceback.print_exception(type(orig), orig, orig.__traceback__)
```

Output:
```
Expected value of type 'TestEnum!', found A; 'A' is not a valid TestEnum

GraphQL request:3:27
2 |     {
3 |         receiveEnum(test: A)
  |                           ^
4 |     }
Traceback (most recent call last):
  File "~/.local/lib/python3.9/site-packages/graphql/validation/rules/values_of_correct_type.py", line 141, in is_valid_value_node
    parse_result = type_.parse_literal(node)
  File "~/.local/lib/python3.9/site-packages/strawberry/schema/schema_converter.py", line 89, in parse_literal
    return self.wrapped_cls(super().parse_literal(value_node, _variables))
  File "/usr/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 677, in __new__
    raise ve_exc
ValueError: 'A' is not a valid TestEnum
```

## System Information

 - Strawberry version: 0.138.1
 - Python version: 3.9.2
 - Operating system: Debian 11

**Comment by patrick91** [comment]
@N-Maas thank you very much for the detailed report! 

I'll make a fix soon 😊

**Comment by patrick91** [comment]
Hey @N-Maas, here's a pre-release: https://github.com/strawberry-graphql/strawberry/pull/2306#issuecomment-1301473705

not 100% sure of the fix, but worth testing it already:)

**Comment by N-Maas** [comment]
Thank you for the quick fix @patrick91, the pre-release works for my use cases :)
