### ISSUE TITLE
FastAPI new release 0.89.1 fixes Pydantic Response types

### ISSUE THREAD

**Issue by m3talstorm** [strawberry-graphql/strawberry#2444]
Installing with `strawberry-graphql[fastapi]==0.152.0` will grab `fastapi==0.89.0`

Following the tutorial with:

```Python
import strawberry

from fastapi import FastAPI, Depends, Request, WebSocket, BackgroundTasks
from strawberry.types import Info
from strawberry.fastapi import BaseContext, GraphQLRouter


class CustomContext(BaseContext):
    def __init__(self, greeting: str, name: str):
        self.greeting = greeting
        self.name = name


def custom_context_dependency() -> CustomContext:
    return CustomContext(greeting="you rock!", name="John")


async def get_context(
    custom_context=Depends(custom_context_dependency),
):
    return custom_context


@strawberry.type
class Query:
    @strawberry.field
    def example(self, info: Info) -> str:
        return f"Hello {info.context.name}, {info.context.greeting}"

schema = strawberry.Schema(Query)

graphql_app = GraphQLRouter(
  schema,
  context_getter=get_context,
)

app = FastAPI()
app.include_router(graphql_app, prefix="/graphql")
```

Will give the exception:

```Python
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 404, in main
    run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/ele/stream/app.py", line 36, in <module>
    graphql_app = GraphQLRouter(
  File "/usr/local/lib/python3.10/site-packages/strawberry/fastapi/router.py", line 159, in __init__
    async def handle_http_get(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 633, in decorator
    self.add_api_route(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 572, in add_api_route
    route = route_class(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 400, in __init__
    self.response_field = create_response_field(
  File "/usr/local/lib/python3.10/site-packages/fastapi/utils.py", line 90, in create_response_field
    raise fastapi.exceptions.FastAPIError(
fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that <class 'starlette.responses.Response'> is a valid pydantic field type
```

fastapi 0.89.0 has this issue raised here: https://github.com/tiangolo/fastapi/issues/5861
fastapi 0.89.1 has just been released, bumping the poetry lock file will probably be a good idea :)

Installing `fastapi==0.89.1` specially instead of strawberry-graphql[fastapi] fixes the issue.

**Comment by patrick91** [comment]
@m3talstorm I don't think the lock file would change much :D We have a PR for it though, I'll merge it soon!

I've just tried the command and installed the latest version of FastAPI:

```
/private/tmp/lol .virtualenv ❯ pip install "strawberry-graphql[fastapi]==0.152.0"
Collecting strawberry-graphql[fastapi]==0.152.0
  Downloading strawberry_graphql-0.152.0-py3-none-any.whl (213 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.6/213.6 kB 8.1 MB/s eta 0:00:00
Collecting fastapi>=0.65.2
  Downloading fastapi-0.89.1-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 6.5 MB/s eta 0:00:00
Collecting graphql-core<3.3.0,>=3.2.0
```

I'll close the issue when I merge the other PR though :)

**Comment by patrick91** [comment]
I've merged the PR for updating the lock file 😊
