### ISSUE TITLE
new strawberry.lazy not compatible with from __future__ import annotations

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry#2504]
# Description

The new way of lazy referencing via strawberry.lazy is not compatible with 
`from __future__ import annotations`

It would be nice to have compatibility as typing.Self is not available for python <=3.10 (the main reason to have `from __future__ import annotations`)

**Comment by ThirVondukr** [comment]
Can confirm this: https://gitlab.com/ThirVondukr/strawberry-annotations
```py
Traceback (most recent call last):
  File "strawberry-annnotations\app.py", line 16, in <module>
    schema = Schema(
             ^^^^^^^
  File "strawberry-annnotations\.venv\Lib\site-packages\strawberry\schema\schema.py", line 157, in __init__
    raise error.__cause__ from None
  File "strawberry-annnotations\.venv\Lib\site-packages\graphql\type\definition.py", line 808, in fields
    fields = resolve_thunk(self._fields)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strawberry-annnotations\.venv\Lib\site-packages\graphql\type\definition.py", line 300, in resolve_thunk
    return thunk() if callable(thunk) else thunk
           ^^^^^^^
  File "strawberry-annnotations\.venv\Lib\site-packages\strawberry\schema\schema_converter.py", line 423, in <lambda>
    fields=lambda: self.get_graphql_fields(object_type),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strawberry-annnotations\.venv\Lib\site-packages\strawberry\schema\schema_converter.py", line 312, in get_graphql_fields
    return self._get_thunk_mapping(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "strawberry-annnotations\.venv\Lib\site-packages\strawberry\schema\schema_converter.py", line 302, in _get_thunk_mapping
    raise UnresolvedFieldTypeError(type_definition, field)
strawberry.exceptions.unresolved_field_type.UnresolvedFieldTypeError: Could not resolve the type of 'b'. Check that the class is accessible from the global module scope.
```
