### ISSUE TITLE
Private fields don't work with pydantic

### ISSUE THREAD

**Issue by lachlancoding** [strawberry-graphql/strawberry#2674]
## Describe the Bug
If you try to make a strawberry type from a pydantic class but mask out one of the fields in the pydantic class by making it private, it produces a key error.

class MyPydanticClass(BaseModel):
  a_field: int
  b_field: int

@strawberry.experimental.pydantic.type(model=NewVrmOrder
class MyStrawberryClass(model=MyPydanticClass):
  a_field: strawberry.auto
  b_field: strawberry.Private[int]

Traceback (most recent call last):
  File "/home/lachlanstanding/workspace/myterra-backend/example.py", line 11, in <module>
    class MyStrawberryClass:
  File "/home/lachlanstanding/workspace/ctvenv/lib/python3.8/site-packages/strawberry/experimental/pydantic/object_type.py", line 175, in wrap
    all_model_fields: List[DataclassCreationFields] = [
  File "/home/lachlanstanding/workspace/ctvenv/lib/python3.8/site-packages/strawberry/experimental/pydantic/object_type.py", line 176, in <listcomp>
    _build_dataclass_creation_fields(
  File "/home/lachlanstanding/workspace/ctvenv/lib/python3.8/site-packages/strawberry/experimental/pydantic/object_type.py", line 63, in _build_dataclass_creation_fields
    else existing_fields[field.name].type
KeyError: 'b_field'

**Comment by lvalladares** [comment]
I can confirm this still happens, it seems to be related to a validation that forces you to put strawberry.auto as the type of any attribute that exists in the pydantic class.

So far, I haven't found a way of making a pydantic field private

**Comment by Ivan-Vinitskyi** [comment]
I meet the same problem.

**Comment by patrick91** [comment]
Fixed in https://github.com/strawberry-graphql/strawberry/pull/4179
