### ISSUE TITLE
The response parameter of the get_context method in asgi has no default value

### ISSUE THREAD

**Issue by star2000** [strawberry-graphql/strawberry#2713]
https://github.com/strawberry-graphql/strawberry/blob/5fb0532bcf96d6bdaa6cdc35c35a2dd4d9e76bf9/strawberry/asgi/__init__.py#L152-L155
https://github.com/strawberry-graphql/strawberry/blob/5fb0532bcf96d6bdaa6cdc35c35a2dd4d9e76bf9/strawberry/asgi/handlers/graphql_transport_ws_handler.py#L35-L36

**Comment by star2000** [comment]
eg.
```py
    @subscription
    async def time(self) -> AsyncGenerator[float, None]:
        while True:
            yield time()
            await asyncio.sleep(1)

```
```gql
subscription {
  time
}
```
```
INFO:     ('127.0.0.1', 59729) - "WebSocket /api/" [accepted]
INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\channels\routing.py", line 62, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\channels\middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\channels\routing.py", line 116, in __call__
    return await application(
           ^^^^^^^^^^^^^^^^^^
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\strawberry\asgi\__init__.py", line 118, in __call__       
    await self.graphql_transport_ws_handler_class(
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\websockets\legacy\protocol.py", line 766, in close    await self.write_close_frame(Close(code, reason))
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\websockets\legacy\protocol.py", line 1232, in write_close_frame 
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\websockets\legacy\protocol.py", line 1205, in write_frame           await self.drain()
  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\websockets\legacy\protocol.py", line 1194, in drain
    await self.ensure_open()  File "C:\code\jzfw\jzfw-server\.venv\Lib\site-packages\websockets\legacy\protocol.py", line 935, in ensure_open        
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame receivedINFO:     connection closed
```
Return to normal after adding the following code
```py
from strawberry.asgi import GraphQL

async def get_context(self, request, response=None):
    return {"request": request, "response": response}

GraphQL.get_context = get_context  # type:ignore

```

**Comment by erivlis** [comment]
I encountered this issue too.

strawberry-graphql[asgi,opentelemetry]==0.171.1
uvicorn[standard]==0.21.1
websockets==10.4

also tested:
websockets==11.0.2
