### ISSUE TITLE
relay: returning an strawberry object with node: strawberry.relay.Node = strawberry.relay.node() breaks

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry#2923]
After the latest strawberry / strawberry django updates, the code

```` python

@strawberry.type
class SecretgraphObject:
    node: strawberry.relay.Node = strawberry.relay.node()

@strawberry.type
class Query:
    @strawberry_django.field
    @staticmethod
    def secretgraph(
        info: Info, authorization: Optional[AuthList] = None
    ) -> SecretgraphObject:
        return SecretgraphObject
````

doesn't work anymore.

## System Information

 - Operating system: linux
 - Strawberry version (if applicable): 193.1

## Additional Context

````
GraphQL request:2:3
1 | query serverSecretgraphConfigQuery {
2 |   secretgraph {
  |   ^
3 |     config {
Traceback (most recent call last):
  File "/home/alex/git/secretgraph/.venv/lib/python3.11/site-packages/graphql/execution/execute.py", line 528, in await_result
    return_type, field_nodes, info, path, await result
                                          ^^^^^^^^^^^^
  File "/home/alex/git/secretgraph/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/git/secretgraph/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/git/secretgraph/.venv/lib/python3.11/site-packages/strawberry_django/resolvers.py", line 91, in async_resolver
    return sync_resolver(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/git/secretgraph/.venv/lib/python3.11/site-packages/strawberry_django/resolvers.py", line 77, in sync_resolver
    retval = retval()
             ^^^^^^^^
TypeError: SecretgraphObject.__init__() missing 1 required keyword-only argument: 'node'
````

**Comment by patrick91** [comment]
@devkral do you still get this? 

can you do a reproduction here? https://play.strawberry.rocks/

**Comment by devkral** [comment]
I think it is fixed, I tried to provoke the error in my code without success
