### ISSUE TITLE
Going from  0.203.1 -> 0.203.3 will break PaginationWindow

### ISSUE THREAD

**Issue by Zorking** [strawberry-graphql/strawberry#3036]
## Describe the Bug

Updating from 0.203.1 to 0.203.3 is breaking [PaginationWindow](https://strawberry.rocks/docs/guides/pagination/offset-based)  from the guide. Everything works fine on 0.203.1.

PaginationWindow classes will disappear from auto-generated doc All Schema Types section. 

Requests will result in an errors like:
```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field 'items' on type 'Employee'. Did you mean 'teams'?",
      "locations": [
        {
          "line": 10,
          "column": 5
        }
      ]
    },
    {
      "message": "Cannot query field 'totalItemsCount' on type 'Employee'.",
      "locations": [
        {
          "line": 16,
          "column": 5
        }
      ]
    },
    {
      "message": "Cannot query field 'functionResponse' on type 'Employee'.",
      "locations": [
        {
          "line": 17,
          "column": 5
        }
      ]
    }
  ]
}

```
<details>
  <summary>My code</summary>
    
  ```python
  from typing import TypeVar, Optional, List

import strawberry

GenericType = TypeVar("GenericType")  # type: ignore


@strawberry.type
class PaginationWindow(List[GenericType]):  # type: ignore
    items: List[GenericType] = strawberry.field()  # type: ignore

    total_items_count: int = strawberry.field()
    function_response: Optional[int] = strawberry.field()
  ```
  
</details>

</details>

<details>
  <summary>Traceback</summary>

  ```
GraphQL request:10:5
 9 |   ) {
10 |     items {
   |     ^
11 |       id
Stack (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/strawberry/asgi/__init__.py", line 111, in __call__
    return await self.handle_http(scope, receive, send)
  File "venv/lib/python3.10/site-packages/strawberry/asgi/__init__.py", line 178, in handle_http
    response = await self.run(request)
  File "venv/lib/python3.10/site-packages/strawberry/http/async_base_view.py", line 176, in run
    result = await self.execute_operation(
  File "venv/lib/python3.10/site-packages/strawberry/http/async_base_view.py", line 115, in execute_operation
    return await self.schema.execute(
  File "venv/lib/python3.10/site-packages/strawberry/schema/schema.py", line 256, in execute
    result = await execute(
  File "venv/lib/python3.10/site-packages/strawberry/schema/execute.py", line 126, in execute
    process_errors(execution_context.errors, execution_context)
Cannot query field 'totalItemsCount' on type 'Employee'.

GraphQL request:16:5
15 |     }
16 |     totalItemsCount
   |     ^
17 |     functionResponse
Stack (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/strawberry/asgi/__init__.py", line 111, in __call__
    return await self.handle_http(scope, receive, send)
  File "venv/lib/python3.10/site-packages/strawberry/asgi/__init__.py", line 178, in handle_http
    response = await self.run(request)
  File "venv/lib/python3.10/site-packages/strawberry/http/async_base_view.py", line 176, in run
    result = await self.execute_operation(
  File "venv/lib/python3.10/site-packages/strawberry/http/async_base_view.py", line 115, in execute_operation
    return await self.schema.execute(
  File "venv/lib/python3.10/site-packages/strawberry/schema/schema.py", line 256, in execute
    result = await execute(
  File "venv/lib/python3.10/site-packages/strawberry/schema/execute.py", line 126, in execute
    process_errors(execution_context.errors, execution_context)
Cannot query field 'functionResponse' on type 'Employee'.

GraphQL request:17:5
16 |     totalItemsCount
17 |     functionResponse
   |     ^
18 |   }
Stack (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "venv/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "venv/lib/python3.10/site-packages/strawberry/asgi/__init__.py", line 111, in __call__
    return await self.handle_http(scope, receive, send)
  File "venv/lib/python3.10/site-packages/strawberry/asgi/__init__.py", line 178, in handle_http
    response = await self.run(request)
  File "venv/lib/python3.10/site-packages/strawberry/http/async_base_view.py", line 176, in run
    result = await self.execute_operation(
  File "venv/lib/python3.10/site-packages/strawberry/http/async_base_view.py", line 115, in execute_operation
    return await self.schema.execute(
  File "venv/lib/python3.10/site-packages/strawberry/schema/schema.py", line 256, in execute
    result = await execute(
  File "venv/lib/python3.10/site-packages/strawberry/schema/execute.py", line 126, in execute
    process_errors(execution_context.errors, execution_context)
INFO:     127.0.0.1:52398 - "POST / HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "venv/lib/python3.10/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "venv/lib/python3.10/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "venv/lib/python3.10/site-packages/uvicorn/main.py", line 582, in run
    ChangeReload(config, target=server.run, sockets=[sock]).run()
  File "venv/lib/python3.10/site-packages/uvicorn/supervisors/basereload.py", line 50, in run
    for changes in self:
  File "venv/lib/python3.10/site-packages/uvicorn/supervisors/basereload.py", line 69, in __next__
    return self.should_restart()
  File "venv/lib/python3.10/site-packages/uvicorn/supervisors/statreload.py", line 32, in should_restart
    for file in self.iter_py_files():
  File "venv/lib/python3.10/site-packages/uvicorn/supervisors/statreload.py", line 52, in iter_py_files
    for path in list(reload_dir.rglob("*.py")):
  File "/usr/lib/python3.10/pathlib.py", line 1047, in rglob
    for p in selector.select_from(self):
  File "/usr/lib/python3.10/pathlib.py", line 493, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/usr/lib/python3.10/pathlib.py", line 440, in _select_from
    with scandir(parent_path) as scandir_it:
FileNotFoundError: [Errno 2] No such file or directory: 'venv/lib/python3.10/site-packages/~ython_multipart-0.0.6.dist-info'

  ```
</details>

## System Information

 - Operating system: Ubuntu 22.04.2
 - Strawberry version (if applicable): 0.203.3

**Comment by Zorking** [comment]
@patrick91 
https://play.strawberry.rocks/?version=0.203.3&gist=7bf58cd002940e656b5ff913d1bd4f45

**Comment by patrick91** [comment]
@Zorking why are you subclassing typing.List in `class PaginationWindow(typing.List[GenericType])`?

**Comment by AlexTo** [comment]
happens to me too, I was using 0.200.0 with PaginationWindow working and upgrading to the latest 0.203.3 breaks it

**Comment by AlexTo** [comment]
0.203.2 does not work too but downgrading to 0.203.1 works

**Comment by Zorking** [comment]
> @Zorking why are you subclassing typing.List in `class PaginationWindow(typing.List[GenericType])`?

@patrick91 this is how it was written in the [docs](https://strawberry.rocks/docs/guides/pagination/offset-based )  and that was working. If pagination should be used differently, we can just change the doc.

**Comment by patrick91** [comment]
> > @Zorking why are you subclassing typing.List in `class PaginationWindow(typing.List[GenericType])`?
> 
> 
> 
> @patrick91 this is how it was written in the [docs](https://strawberry.rocks/docs/guides/pagination/offset-based )  and that was working. If pagination should be used differently, we can just change the doc. 

Oh I didn't realise! sorry ☺️

I'll double check, but I think it is wrong to subclass list like that

**Comment by AlexTo** [comment]
hi, just would like to know if this is being fixed? the last version that works is 0.203.1 so I'm stuck at that version although it is not an issue at the moment. 
Thanks, very much appreciated!!

**Comment by AlexTo** [comment]
@patrick91 do you know if recent version of Strawberry has fixed this?

**Comment by patrick91** [comment]
let me take a look, sorry it took me a while to get to this 😊

**Comment by patrick91** [comment]
ok, changing the paginated type to this:

```
        )
@strawberry.type
class PaginationWindow(typing.Generic[GenericType]):
    items: typing.List[GenericType] = strawberry.field(
        description="The list of items in this pagination window."
    )

    total_items_count: int = strawberry.field(
        description="Total number of items in the filtered dataset."
    )
```

Fixes the issue, I'll update the docs and close this issue for now, I don't think we should support subclassing typing.List 😊

**Comment by patrick91** [comment]
@AlexTo if you have the same issue with with a different case feel free to open a new issue 😊

**Comment by AlexTo** [comment]
cool, thanks a lot @patrick91
