### ISSUE TITLE
StrawberryGraphQLError in Custom Extension causes 500 error response instead of formatted error

### ISSUE THREAD

**Issue by staubina** [strawberry-graphql/strawberry#3204]
## Description
I am attempting to add a Custom Extension to catch queries that are too large. I then want the extension to raise StrawberryGraphQLError and return a properly formatted error message. 

The issue is that when I raise StrawberryGraphQLError an internal error response is sent to the requester.

```
MAX_QUERY_LENGTH = 8192 # 8KB

class MaxQueryLengthExtension(SchemaExtension):
    async def on_operation(self):
        if len(self.execution_context.query) > MAX_QUERY_LENGTH:
            raise StrawberryGraphQLError(message="Query too large")
        yield
```

Stack Trace

```
2023-11-06 11:26:31 Exception in ASGI application
2023-11-06 11:26:31 Traceback (most recent call last):
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2023-11-06 11:26:31     result = await app(  # type: ignore[func-returns-value]
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-11-06 11:26:31     return await self.app(scope, receive, send)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
2023-11-06 11:26:31     await super().__call__(scope, receive, send)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
2023-11-06 11:26:31     await self.middleware_stack(scope, receive, send)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/ddtrace/contrib/asgi/middleware.py", line 275, in __call__
2023-11-06 11:26:31     reraise(exc_type, exc_val, exc_tb)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/six.py", line 719, in reraise
2023-11-06 11:26:31     raise value
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/ddtrace/contrib/asgi/middleware.py", line 270, in __call__
2023-11-06 11:26:31     return await self.app(scope, receive, wrapped_send)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-11-06 11:26:31     raise exc
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-11-06 11:26:31     await self.app(scope, receive, _send)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
2023-11-06 11:26:31     await self.app(scope, receive, send)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-11-06 11:26:31     raise exc
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-11-06 11:26:31     await self.app(scope, receive, sender)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-11-06 11:26:31     raise e
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-11-06 11:26:31     await self.app(scope, receive, send)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
2023-11-06 11:26:31     await route.handle(scope, receive, send)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
2023-11-06 11:26:31     await self.app(scope, receive, send)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
2023-11-06 11:26:31     response = await func(request)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
2023-11-06 11:26:31     raw_response = await run_endpoint_function(
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
2023-11-06 11:26:31     return await dependant.call(**values)
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/strawberry/fastapi/router.py", line 227, in handle_http_post
2023-11-06 11:26:31     return await self.run(
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/strawberry/http/async_base_view.py", line 176, in run
2023-11-06 11:26:31     result = await self.execute_operation(
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/strawberry/http/async_base_view.py", line 115, in execute_operation
2023-11-06 11:26:31     return await self.schema.execute(
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/strawberry/schema/schema.py", line 256, in execute
2023-11-06 11:26:31     result = await execute(
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/strawberry/schema/execute.py", line 86, in execute
2023-11-06 11:26:31     async with extensions_runner.operation():
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/strawberry/extensions/context.py", line 191, in __aenter__
2023-11-06 11:26:31     await self.run_hooks_async()
2023-11-06 11:26:31   File "/usr/local/lib/python3.9/site-packages/strawberry/extensions/context.py", line 175, in run_hooks_async
2023-11-06 11:26:31     await hook.initialized_hook.__anext__()  # type: ignore[union-attr]
2023-11-06 11:26:31   File "/src/src/routers/graphql.py", line 78, in on_operation
2023-11-06 11:26:31     raise StrawberryGraphQLError(message="Query too large")
2023-11-06 11:26:31 strawberry.exceptions.StrawberryGraphQLError: Query too large
```

## System Information

 - Operating system: Mac with Docker containers
 - Strawberry version (if applicable): `strawberry-graphql[fastapi] == 0.209.2`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3204">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3204/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3204/pledge.svg">
</picture>
</a>

**Comment by DoctorJohn** [comment]
Hey @staubina, with our current implementation this seems to be expected.

You might want to try to add your validation error to the execution context, similar to how our built-in [ValidationCache](https://github.com/strawberry-graphql/strawberry/blob/4130a75f23a7fec7b4a6e9fbba913c4607437f37/strawberry/extensions/validation_cache.py#L36-L45) and [MaskErrors](https://github.com/strawberry-graphql/strawberry/blob/4130a75f23a7fec7b4a6e9fbba913c4607437f37/strawberry/extensions/mask_errors.py#L35-L46) extensions do it. Based on your code this would roughtly look like this:

```python
MAX_QUERY_LENGTH = 8192 # 8KB

class MaxQueryLengthExtension(SchemaExtension):
    async def on_validate(self):
        execution_context = self.execution_context

        if len(self.execution_context.query) > MAX_QUERY_LENGTH:
            error = StrawberryGraphQLError(message="Query too large")
            execution_context.errors = [error]
        yield
```

**Comment by patrick91** [comment]
@jkimbo @DoctorJohn do you remember why we didn't send these errors to the response object?

/cc @erikwrede do you have any opinion on this?

Context: https://github.com/strawberry-graphql/strawberry/pull/1324

**Comment by erikwrede** [comment]
@patrick91 for continuity this should be handled the same way we handle field extension errors or normal resolver errors, like in the permission extension. `[Strawberry/GraphQL-Core]GQLErrors` should automatically be added to the execution context while all other errors should cause an Internal Server error.

**Comment by patrick91** [comment]
> Hey @staubina, with our current implementation this seems to be expected.
> 
> You might want to try to add your validation error to the execution context, similar to how our built-in [ValidationCache](https://github.com/strawberry-graphql/strawberry/blob/4130a75f23a7fec7b4a6e9fbba913c4607437f37/strawberry/extensions/validation_cache.py#L36-L45) and [MaskErrors](https://github.com/strawberry-graphql/strawberry/blob/4130a75f23a7fec7b4a6e9fbba913c4607437f37/strawberry/extensions/mask_errors.py#L35-L46) extensions do it. Based on your code this would roughtly look like this:
> 
> ```python
> MAX_QUERY_LENGTH = 8192 # 8KB
> 
> class MaxQueryLengthExtension(SchemaExtension):
>     async def on_validate(self):
>         execution_context = self.execution_context
> 
>         if len(self.execution_context.query) > MAX_QUERY_LENGTH:
>             error = StrawberryGraphQLError(message="Query too large")
>             execution_context.errors = [error]
>         yield
> ```

I missed your reply before answering! I think this won't work well because we'd have parsed the query by then, and we want to prevent to parse huge strings 😊



> @patrick91 for continuity this should be handled the same way we handle field extension errors or normal resolver errors, like in the permission extension. `[Strawberry/GraphQL-Core]GQLErrors` should automatically be added to the execution context while all other errors should cause an Internal Server error.

So you'd suggest to only handle GraphQL errors in our execute function?


> The Schema Extension error should in any case lead to stopping the request. There should be no way to throw an error during `on_operation` and have the execution continue

Yup, that makes sense!

**Comment by DoctorJohn** [comment]
> I missed your reply before answering! I think this won't work well because we'd have parsed the query by then, and we want to prevent to parse huge strings 😊

Well spotted! OP got it right in their example by using `on_operation` instead of `on_validate`. I adjusted my response.

**Comment by DoctorJohn** [comment]
> So you'd suggest to only handle GraphQL errors in our execute function?

Wondering about that too :) At least from the perspective of integrations, all "normal resolvers errors" are eventually converted into GraphQL(core)Errors and included in the results `errors`. For consistency we probably want any error raised from within extensions to be handled similarly?

**Comment by erikwrede** [comment]
> So you'd suggest to only handle GraphQL errors in our execute function?

> For consistency we probably want any error raised from within extensions to be handled similarly [to one raised from withing resolvers]?

After looking at it again, I believe we should handle all errors the same, no matter if they originate in the extension or in the resolver. The detailed decision of how non-GraphQL Errors are handled could be moved to an ExceptionFilter in the web views.

**Comment by patrick91** [comment]
> After looking at it again, I believe we should handle all errors the same, no matter if they originate in the extension or in the resolver. The detailed decision of how non-GraphQL Errors are handled could be moved to an ExceptionFilter in the web views.

I think so too, we already treat any error inside resolvers as GraphQL errors, it is weird to not do that for parsing and operation errors 😊

@DoctorJohn what do you think?

**Comment by DoctorJohn** [comment]
> I think so too, we already treat any error inside resolvers as GraphQL errors, it is weird to not do that for parsing and operation errors 😊
> 
> @DoctorJohn what do you think?

I agree. Already started working on it. Turns out 83 testc cases depend on the current behaviour. Looks like mainly for assertions within tests. I'll make sure to check whether any public facing and tested behaviour changes.

**Comment by staubina** [comment]
After reading the docs here: https://strawberry.rocks/docs/guides/custom-extensions a few more times, I was able to get the following to work for now. 

Any potential pitfalls I am not seeing yet?

```
from graphql.error import GraphQLError
from graphql import ExecutionResult as GraphQLExecutionResult
.....

MAX_QUERY_LENGTH = 8192 # 8KB


class MaxQueryLengthExtension(SchemaExtension):
    def on_execute(self):
        if len(self.execution_context.query) > MAX_QUERY_LENGTH:
            self.execution_context.result = GraphQLExecutionResult(
                data=None,
                errors=[GraphQLError("Query too large")],
            )


```

**Comment by DoctorJohn** [comment]
> I was able to get the following to work for now.

Good job! You're correct, supplying a result from within the `on_excute` hook will prevent further evaluation.

This is because of this check: https://github.com/strawberry-graphql/strawberry/blob/4130a75f23a7fec7b4a6e9fbba913c4607437f37/strawberry/schema/execute.py#L226-L227

> Any potential pitfalls I am not seeing yet?

Your query will be fully parsed and validated even when it's too long. If your goal is to mitigate DDoS attacks, performing the parsing and validation steps might be unwanted.

**Comment by staubina** [comment]
That was my fear, I would like to stop it at an earlier stage for DDoS protection, but as you are all discussing any level above execute throws a 500. I was not able to determine an approach to catching the exception and handling it in my FastAPI app code.

This is a start at least.
