### ISSUE TITLE
Python code generation from schema has invalid forward type references

### ISSUE THREAD

**Issue by jannikw** [strawberry-graphql/strawberry#3254]
## Describe the Bug

The code generator doesn't seem to produce correct Python type annotations.

Given a simple schema in `schema.graphql`:
```graphql
type Query {
    name: String
    other: Other
}

type Other {
    foo: String
}
```
Running `strawberry schema-codegen schema.graphql` generates the following python code:
```python
import strawberry

@strawberry.type
class Query:
    name: str | None
    other: Other | None # <--- reference to `Other`

@strawberry.type
class Other:
    foo: str | None

schema = strawberry.Schema(query=Query)

```

The class `Query` references `Other` before it is defined. Running the code makes Python complain:
```
Traceback (most recent call last):
  File ".../schema.py", line 4, in <module>
    class Query:
  File ".../schema.py", line 6, in Query
    other: Other | None
           ^^^^^
NameError: name 'Other' is not defined. Did you mean: 'iter'?
```
Possible fixes are:
- Reordering the types so `Other` comes first and thus making the reference valid. This  works as long as the types form no cycle.
- Adding `from __future__ import annotations` to the Python code making forward references legal. See https://mypy.readthedocs.io/en/stable/runtime_troubles.html#class-name-forward-references
- Rewrite the type annotation as `typing.Optional["Other"]` (Note the string quotes). Interestingly, `"Other" | None` is not valid, so `Optional` has to be used here.

## System Information

- Python 3.11.6
 - Operating system: Linux
 - Strawberry version (if applicable): 0.215.1 (most recent)

## Additional Context
Of course, for a small schema those issues can be quickly fixed, but for a large schema this isn't really feasible.

**Comment by jannikw** [comment]
Similarly, forward references in generated union types are also invalid:
```graphql
union U = Foo | Bar

type Foo {
    foo: String
}

type Bar {
    foo: String
}
```
produces the following code:
```python
U = Annotated[Foo | Bar, strawberry.union(name="U")]

@strawberry.type
class Foo:
    foo: str | None

@strawberry.type
class Bar:
    foo: str | None

```
Sadly, `from __future__ import annotations` doesn't solve the issue here. We have to move the union below both classes to make Python happy.

**Comment by patrick91** [comment]
Fixed here https://github.com/strawberry-graphql/strawberry/pull/4192
