### ISSUE TITLE
Forward references with non-builtin types

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#340]
I see that in #17, support for forward references was added, but is this fully implemented? 

If I enable PEP563 and define a field that uses a non-builtin type, I get an exception. Here I took the example from the Getting Started page, imported the annotations future feature, and changed age to an Optional field. This exception doesn't occur when the future feature is not imported.

```python
from __future__ import annotations

import typing

import strawberry


@strawberry.type
class User:
    name: str
    age: typing.Optional[int]


@strawberry.type
class Query:
    @strawberry.field
    def user(self, info) -> User:
        return User(name="Patrick", age=100)


schema = strawberry.Schema(query=Query)
```

```
Traceback (most recent call last):
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/definition.py", line 735, in fields
    fields = resolve_thunk(self._fields)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/definition.py", line 293, in resolve_thunk
    return thunk() if callable(thunk) else thunk
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/type.py", line 133, in <lambda>
    lambda types_replacement_map=None: _get_fields(wrapped, types_replacement_map),
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/type.py", line 76, in _get_fields
    fields[field_name] = field(
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/utils/lazy_property.py", line 8, in _lazy_property
    setattr(self, attr_name, fn(self))
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/field.py", line 105, in graphql_type
    return _get_field(
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/field.py", line 197, in _get_field
    annotations = typing.get_type_hints(wrap, None, get_registered_types())
  File "/usr/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'typing' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ignormies/.config/JetBrains/PyCharm2020.1/scratches/scratch_7.py", line 21, in <module>
    schema = strawberry.Schema(query=Query)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/schema.py", line 25, in __init__
    super().__init__(
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/schema.py", line 205, in __init__
    collect_referenced_types(query)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/schema.py", line 383, in collect_referenced_types
    collect_referenced_types(field.type)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/schema.py", line 382, in collect_referenced_types
    for field in named_type.fields.values():
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/definition.py", line 737, in fields
    raise TypeError(f"{self.name} fields cannot be resolved. {error}")
TypeError: User fields cannot be resolved. name 'typing' is not defined

Process finished with exit code 1
```

**Comment by patrick91** [comment]
@BryceBeagle yes, I remember this failure, I didn't really have time to debug it, but I left a test:

https://github.com/strawberry-graphql/strawberry/blob/master/tests/test_forward_references.py#L1-L25

I'll see if I can fix this, not sure when though :) Do you use

```python
from __future__ import annotations
``` 

a lot?

**Comment by BryceBeagle** [comment]
I'm just getting started with Strawberry actually, so I don't really use _anything_ a lot yet :). I was trying to split all my types into separate files and wanted to use forward references while doing so.

**Comment by patrick91** [comment]
I mean in general. Personally I haven’t used them much 😊

The alternative would be to use quotes around types, which I think should work

**Comment by BryceBeagle** [comment]
Yeah I don't use it forward references all that much, but I was thinking this could have been a good reason to try them out.

Using quotes appears to be working
