### ISSUE TITLE
Can't pass a @classmethod when declaring a field with a resolver

### ISSUE THREAD

**Issue by BryceBeagle** [strawberry-graphql/strawberry#349]
As it exists below, this code snippet runs fine. However, if I switch the commented lines in the Query class I get an exception. Is this to be expected?

```python

import typing

import strawberry
import graphql


@strawberry.type
class User:
    name: str
    age: int

    @classmethod
    def get_users(cls):
        return [
            cls(name="Bob", age=10),
            cls(name="Nancy", age=30)
        ]


def get_users():
    return User.get_users()


@strawberry.type
class Query:
    # users: typing.List[User] = strawberry.field(resolver=User.get_users)
    users: typing.List[User] = strawberry.field(resolver=get_users)


schema = strawberry.Schema(query=Query)

query = "{ users { name } }"

result = graphql.graphql_sync(schema, query)

print(result.data)
```

```
Traceback (most recent call last):
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/definition.py", line 735, in fields
    fields = resolve_thunk(self._fields)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/definition.py", line 293, in resolve_thunk
    return thunk() if callable(thunk) else thunk
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/type.py", line 133, in <lambda>
    lambda types_replacement_map=None: _get_fields(wrapped, types_replacement_map),
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/type.py", line 76, in _get_fields
    fields[field_name] = field(
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/field.py", line 315, in field
    return field(wrap)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/field.py", line 171, in __call__
    setattr(wrap, IS_STRAWBERRY_FIELD, True)
AttributeError: 'method' object has no attribute '_is_strawberry_field'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ignormies/.config/JetBrains/PyCharm2020.1/scratches/scratch_7.py", line 30, in <module>
    schema = strawberry.Schema(query=Query)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/strawberry/schema.py", line 25, in __init__
    super().__init__(
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/schema.py", line 205, in __init__
    collect_referenced_types(query)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/schema.py", line 382, in collect_referenced_types
    for field in named_type.fields.values():
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/ignormies/.local/share/virtualenvs/gql-bf-XGX4szKA-py3.8/lib/python3.8/site-packages/graphql/type/definition.py", line 737, in fields
    raise TypeError(f"{self.name} fields cannot be resolved. {error}")
TypeError: Query fields cannot be resolved. 'method' object has no attribute '_is_strawberry_field'

Process finished with exit code 1
```

**Comment by patrick91** [comment]
Oh interesting bug! Will have a look at it tonight :)

**Comment by patrick91** [comment]
Oh, this is a bit more complicated than expected since we assign a property to the resolvers to let strawberry know, but I think we can do two things:

1. Wrap the resolver (which I don't like)
2. Rewrite how we generate the types: https://github.com/strawberry-graphql/strawberry/issues/313

I think option 2 would be the best. But it will take me a bit of time to get to that :)
