### ISSUE TITLE
strawberry.ext.mypy_plugin Pydantic 2.9.0 PydanticModelField.to_argument error missing 'model_strict' and 'is_root_model_root'

### ISSUE THREAD

**Issue by victor-nb** [strawberry-graphql/strawberry#3631]
Hello!

It seems the Pydantic 2.9.0 version introduced a breaking change on PydanticModelField.to_argument adding two new arguments:

https://github.com/pydantic/pydantic/commit/d6df62aaa34c21272cb5fcbcbe3a8b88474732f8
and 
https://github.com/pydantic/pydantic/commit/93ced97b00491da4778e0608f2a3be62e64437a8

## Describe the Bug

This is the mypy trace

```
./my-file.py:132: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.11.2
Traceback (most recent call last):
  File "mypy/semanal.py", line 7087, in accept
  File "mypy/nodes.py", line 1183, in accept
  File "mypy/semanal.py", line 1700, in visit_class_def
  File "mypy/semanal.py", line 1891, in analyze_class
  File "mypy/semanal.py", line 1925, in analyze_class_body_common
  File "mypy/semanal.py", line 1996, in apply_class_plugin_hooks
  File "/Users/victorbarroncas/code/boostsec-asset-management/.venv/lib/python3.12/site-packages/strawberry/ext/mypy_plugin.py", line 489, in strawberry_pydantic_class_callback
    f.to_argument(
TypeError: PydanticModelField.to_argument() missing 2 required positional arguments: 'model_strict' and 'is_root_model_root'
./my-file.py:132: : note: use --pdb to drop into pdb
```

## System Information

- Operating system: OSX
- strawberry-graphql 0.240.3
- pydantic 2.9.1
- pydantic-core 2.23.3
- mypy 1.11.2
- mypy-extensions 1.0.0

## Additional Context

Similar issue:
https://github.com/strawberry-graphql/strawberry/issues/3560

**Comment by mausch** [comment]
Duplicate of https://github.com/strawberry-graphql/strawberry/issues/3436 ? Seems it's been fixed already

**Comment by patrick91** [comment]
@mausch I think so! thanks for checking!
